version: 2.1
jobs:
  build:
    docker:
      - image: cimg/go:1.21
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Dagger CLI
          command: cd /usr/local && { curl -L https://dl.dagger.io/dagger/install.sh | sudo sh; cd -; }
      - run:
          name: Scan Code References
          command: dagger -m ci call ci  --token=$LD_ACCESS_TOKEN --dir .
      - run:
          name: Stop Dagger Engine
          command: docker stop -t 300 $(docker ps --filter name="dagger-engine-*" -q)
          when: always
workflows:
  dagger:
    jobs:
      - build